from __future__ import annotations

from datetime import datetime, timedelta
from typing import Any

from googleapiclient.discovery import build

from app.config import settings
from app.tools.gmail_tools import get_google_credentials


def build_calendar_service(
    interactive: bool = False,
    *,
    user_id: str | None = None,
):
    creds = get_google_credentials(interactive=interactive, user_id=user_id)
    return build("calendar", "v3", credentials=creds)


def create_followup_event(
    summary: str,
    start_iso: str,
    end_iso: str,
    description: str = "",
    timezone_str: str | None = None,
    *,
    user_id: str | None = None,
) -> dict[str, Any]:
    normalized_summary = summary.strip()
    if not normalized_summary:
        raise ValueError("Calendar event summary cannot be empty.")

    start_dt = datetime.fromisoformat(start_iso)
    end_dt = datetime.fromisoformat(end_iso)
    if end_dt <= start_dt:
        raise ValueError("Calendar event end time must be after its start time.")

    service = build_calendar_service(interactive=False, user_id=user_id)
    effective_timezone = timezone_str or settings.default_timezone

    event_body = {
        "summary": normalized_summary,
        "description": description.strip(),
        "start": {
            "dateTime": start_dt.isoformat(),
            "timeZone": effective_timezone,
        },
        "end": {
            "dateTime": end_dt.isoformat(),
            "timeZone": effective_timezone,
        },
    }

    event = (
        service.events()
        .insert(calendarId="primary", body=event_body)
        .execute()
    )

    return {
        "event_id": event.get("id", ""),
        "html_link": event.get("htmlLink", ""),
    }


def build_followup_event_payload(
    company: str,
    role: str,
    followup_date: str,
    timezone_str: str | None = None,
) -> dict[str, str]:
    normalized_company = company.strip()
    normalized_role = role.strip()
    if not normalized_company:
        raise ValueError("company cannot be empty.")
    if not normalized_role:
        raise ValueError("role cannot be empty.")

    try:
        parsed_date = datetime.strptime(followup_date, "%Y-%m-%d")
    except ValueError as exc:
        raise ValueError("followup_date must use the YYYY-MM-DD format.") from exc

    start_dt = parsed_date.replace(hour=9)
    end_dt = start_dt + timedelta(minutes=30)
    effective_timezone = timezone_str or settings.default_timezone

    summary = f"Follow up — {normalized_company} — {normalized_role}"
    description = (
        f"Follow up on application for {normalized_role} at {normalized_company}.\n"
        "Generated by JobCopilot."
    )

    return {
        "summary": summary,
        "description": description,
        "start_iso": start_dt.isoformat(),
        "end_iso": end_dt.isoformat(),
        "timezone_str": effective_timezone,
    }
