from __future__ import annotations

from datetime import datetime, timedelta
from typing import Any

from googleapiclient.discovery import build

from app.tools.gmail_tools import get_google_credentials


def build_calendar_service(interactive: bool = False):
    creds = get_google_credentials(interactive=interactive)
    return build("calendar", "v3", credentials=creds)


def create_followup_event(
    summary: str,
    start_iso: str,
    end_iso: str,
    description: str = "",
    timezone_str: str = "Europe/Paris",
) -> dict[str, Any]:
    service = build_calendar_service(interactive=False)

    event_body = {
        "summary": summary,
        "description": description,
        "start": {
            "dateTime": start_iso,
            "timeZone": timezone_str,
        },
        "end": {
            "dateTime": end_iso,
            "timeZone": timezone_str,
        },
    }

    event = (
        service.events()
        .insert(calendarId="primary", body=event_body)
        .execute()
    )

    return {
        "event_id": event.get("id", ""),
        "html_link": event.get("htmlLink", ""),
    }


def build_followup_event_payload(
    company: str,
    role: str,
    followup_date: str,
    timezone_str: str = "Europe/Paris",
) -> dict[str, str]:
    start_dt = datetime.fromisoformat(f"{followup_date}T09:00:00")
    end_dt = start_dt + timedelta(minutes=30)

    summary = f"Follow up — {company} — {role}"
    description = (
        f"Follow up on application for {role} at {company}.\n"
        f"Generated by JobCopilot."
    )

    return {
        "summary": summary,
        "description": description,
        "start_iso": start_dt.isoformat(),
        "end_iso": end_dt.isoformat(),
        "timezone_str": timezone_str,
    }